### ISSUE TITLE
Add auto-scaling to our instance

### ISSUE THREAD

**Issue by AlyxPractice** [3615-computer/mastodon#2]
Fly.io has a native way to auto-scale based on requests/concurrency.

The [last time I tried](https://community.fly.io/t/auto-stop-machines-start-machines-keep-getting-restarted/14010?u=alyx), it was buggy using their `http_service` but I think it would work with `services` (https://fly.io/docs/reference/configuration/#services-concurrency).

**Comment by AlyxPink** [comment]
Closing as auto-scaling has never been necessary.
