### ISSUE TITLE
 Change Your Post Character Limit to 1024

### ISSUE THREAD

**Issue by spinning-fantasies** [3615-computer/mastodon#6]
👉 https://write.as/sweetmeat/customize-mastodon-to-change-your-post-character-limit

**Comment by AlyxPractice** [comment]
Hello, thanks for creating the issue!

At the moment, there is no plan to change the character limit. Threads are more than welcome for longer posts, and if it's extremely long, then a blog post should do it.

I'm actually working on a blogging platform for [3615.computer](https://3615.computer) that might solve the issue.

I don't want to edit manually the sources to unlock such features too, it could make the maintenance more complicated in the long run.
